url: "https://khanhnguyenthedeveloper.github.io"

title: Home | Khanh Nguyen Developer
description: Hacker is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
