remote_theme: pages-themes/hacker@master
plugins:
- jekyll-remote-theme
title: Modern Hacker theme
description: Modern Hacker is a theme for GitHub Pages.
theme: jekyll-theme-modern-hacker
show_downloads: true
google:
  tag_manager:
  analytics:
